import { RosesThemeObject } from "roses"

export const styles: RosesThemeObject["styles"] = {
  root: { fontFamily: "body", lineHeight: "body", fontWeight: "body" },
  h1: {
    color: "text",
    fontFamily: "heading",
    lineHeight: "1.2",
    fontWeight: "heading",
    fontSize: 5,
  },
  h2: {
    color: "text",
    fontFamily: "heading",
    lineHeight: "1.2",
    fontWeight: "heading",
    fontSize: 4,
  },
  h3: {
    color: "text",
    fontFamily: "heading",
    lineHeight: "1.2",
    fontWeight: "heading",
    fontSize: 3,
  },
  h4: {
    color: "text",
    fontFamily: "heading",
    lineHeight: "1.2",
    fontWeight: "heading",
    fontSize: 2,
  },
  h5: {
    color: "text",
    fontFamily: "heading",
    lineHeight: "1.2",
    fontWeight: "heading",
    fontSize: 1,
  },
  h6: {
    color: "text",
    fontFamily: "heading",
    lineHeight: "1.2",
    fontWeight: "heading",
    fontSize: 0,
  },
  p: {
    color: "text",
    fontFamily: "body",
    fontWeight: "body",
    lineHeight: "body",
    fontSize: [1, 2],
  },
  li: {
    color: "text",
    fontFamily: "body",
    fontWeight: "body",
    lineHeight: "body",
  },
  a: { color: "primary" },
  pre: { fontFamily: "monospace", overflowX: "auto" },
  code: { fontFamily: "monospace", fontSize: "inherit" },
  table: {
    py: 2,
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: 0,
    fontFamily: "body",
    border: "1px solid",
    borderColor: "text",
  },
  th: {
    textAlign: "center",
    borderBottomStyle: "solid",
    borderBottomWidth: "2px",
  },
  td: {
    py: 2,
    textAlign: "center",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
  },
}
